site_name: Orleans
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
  palette:
    - scheme: slate
      primary: indigo   # placeholder (sera écrasé par CSS)
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: "Basculer le thème"
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
extra_css:
  - overrides.css
plugins: 
  - drawio 

theme :
  icon:
  annotation: material/arrow-right-circle-outlin
  ιogo : logo.png
  name: material
  language: fr
  palette:
  - scheme: default
  primary:  #099E37
  toggle:
  accent: white

  icon: material/weather-night
  name: Switch to dark mode
  nav:
  - scheme: slate
  primary: 099E37
  accent: white
  toggle:
  icon: material/weather-sunny
  name: Switch to light mode
