site_name: Orleans
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
  palette:
    - scheme: slate           
      primary: Deep Orange          
      accent: Deep Orange            
      toggle:
        icon: material/toggle-switch-off-outline
        name: "Basculer le thème"
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - admonition      
  - codehilite      
  - toc             
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
nav:
  - Accueil: index.md
  - Problèmes rencontrés: Problèmes rencontrés.md
  - Taches realiser: taches_realiser.md
  - Équipements: Équipements.md
    
