site_name: Orleans
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
  palette:
    - scheme: slate
      primary: indigo   # placeholder (sera écrasé par CSS)
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: "Basculer le thème"
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
extra_css:
  - overrides.css
plugins: 
  - drawio 

theme:
  name: material
  language: fr
  palette:

    # --- MODE CLAIR ---
    - scheme: default
      primary: "#099E37"
      accent: "#099E37"
      toggle:
        icon: material/weather-night
        name: Passer au mode sombre

    # --- MODE SOMBRE ---
    - scheme: slate
      primary: "#099E37"
      accent: "#099E37"
      toggle:
        icon: material/weather-sunny
        name: Passer au mode clair

extra:
  css:
    - overrides.css
